spring:
  datasource:
   # url: jdbc:mysql://localhost:3306/calculator?serverTimezone=UTC
    #username: root
    #password: 
  url: jdbc:mysql://mysqldb:3306/calculator?serverTimezone=UTC
  username: stevy
  password: manounou

  jpa:
    hibernate:
      ddl-auto: update

  #disable liquibase at start-up
  liquibase:
    enabled: false

server:
  port: 9001