apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "calculator.fullname" . }}-config
data:
  application.yaml: |
    spring:
      jpa:
        hibernate:
          ddl-auto: none
      liquibase:
        enabled: true
