env:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-dev.svc.cluster.local:3306/calculator?serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: dev-secret
  SPRING_PROFILES_ACTIVE: dev

image:
  repository: stevymonkam/calculator-dev
  tag: "2-stable"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30087
